Repository AESInsight/Frontend, pull requests merged in 2025-05, with the labels that each got.

#197 Release
  CHANGELOG.md
  bun.lockb
  dist/assets/index-BFe2l1pZ.js
  dist/assets/index-CKFojc4c.css
  dist/assets/index-DF67PE1I.css
  dist/assets/index-DTiXjdHn.js
  dist/index.html
  index.css
  package.json
  src/components/charts/context/chart_context.tsx
  src/components/charts/gender_salary_bar_chart.tsx
  src/components/charts/grouped_charts.tsx
  src/components/charts/position_bar_chart.tsx
  src/components/charts/salary_pie_chart.tsx
  src/components/charts/salary_raise_flow_chart.tsx
  src/components/charts/toggles/sync_industry_toggle.tsx
  src/components/charts/toggles/sync_jobtitle_toggle.tsx
  src/components/fields/input_field.tsx
  src/components/fields/password_field.tsx
  src/components/modals/login_modal.tsx
  src/components/modals/resetpassword_modal.tsx
  src/components/pages/adminpage.tsx
  src/components/pages/homepage.tsx
  src/components/tables/EmployeeTable.tsx
  src/components/ui/card.tsx
  src/components/ui/chart.tsx
  src/components/ui/checkbox.tsx
  src/components/ui/select.tsx
  src/components/ui/sidebar.tsx
  src/config.ts
  src/lib/companyAPI.ts
  src/lib/employeeAPI.ts
  src/lib/loginAPI.ts
  src/lib/regexValidationLogin.ts
  src/lib/types/salary.ts
  tsconfig.app.tsbuildinfo
Labels: release

#207 feat: edit modal updates data in db, and new status modal for success/error messages when updating data
  src/components/buttons/edit_button.tsx
  src/components/charts/gender_salary_bar_chart.tsx
  src/components/charts/position_bar_chart.tsx
  src/components/charts/salary_pie_chart.tsx
  src/components/charts/salary_raise_flow_chart.tsx
  src/components/modals/edit_modal.tsx
  src/components/modals/status_modal.tsx
  src/components/tables/EmployeeTable.tsx
  src/components/ui/select.tsx
  src/components/ui/sidebar.tsx
  src/lib/employeeAPI.ts
Labels: feature

#199 feat: adds alphabetical and numerical filtering for employee table
  dist/assets/index-B7newsC4.css
  dist/assets/index-C99vHULR.js
  dist/assets/index-DS20ADyi.css
  dist/assets/index-aaBefOUk.js
  dist/index.html
  src/components/tables/EmployeeTable.tsx
  tsconfig.app.tsbuildinfo
Labels: feature

#196 Feat/189/reset-password-page
  dist/assets/index-BQDIqdmX.css
  dist/assets/index-CIUq3Tak.js
  dist/index.html
  src/App.tsx
  src/components/fields/input_field.tsx
  src/components/pages/resetpasswordpage.tsx
  src/components/pages/resetsuccess.tsx
  src/lib/loginAPI.ts
  tsconfig.app.tsbuildinfo
Labels: feature

#237 fix: Add employee button visible when you have no employees
  src/components/pages/adminpage.tsx
Labels: bug, fix
